[package]
name = "superposition_types"
version = "0.9.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# env
actix-web = { workspace = true, optional = true }
anyhow = { workspace = true, optional = true }
bigdecimal = { workspace = true }
chrono = { workspace = true }
derive_more = { workspace = true }
diesel = { workspace = true, optional = true }
diesel-derive-enum = { version = "2.0.1", features = [
    "postgres",
], optional = true }
jsonlogic = { workspace = true }
log = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
service_utils = { version = "0.24.2", path = "../service_utils" }
strum_macros = { workspace = true, optional = true }
superposition_derives = { path = "../superposition_derives", optional = true }
superposition_proc_macros = { path = "../superposition_proc_macros", optional = true }
thiserror = { version = "1.0.57", optional = true }
uuid = { workspace = true }

[features]
default = ["server"]
diesel_derives = [
    "dep:diesel",
    "dep:superposition_derives",
    "dep:diesel-derive-enum",
]
disable_db_data_validation = []
result = ["dep:diesel", "dep:anyhow", "dep:thiserror", "dep:actix-web"]
server = ["dep:actix-web"]
experimentation = ["dep:strum_macros"]

[lints]
workspace = true
